{
 "title": "pi2",
 "time": { "from": "2026-02-16T19:08:35.722Z", "to": "2026-02-16T20:59:47.069Z" },
 "panels": [
  {
   "title": "4SD - timer",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "set = from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      r.code == \"4SD_SET\" and\r\n      r._field == \"value_num\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) }))\r\n\r\nrun = from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      r.code == \"4SD_RUN\" and\r\n      r._field == \"value_bool\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with _value: if r._value then 1 else 0\r\n  }))\r\n\r\nunion(tables: [set, run])\r\n  |> keep(columns: [\"_time\", \"_value\", \"code\"])\r\n"
    }
   ]
  },
  {
   "title": "GSG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      (r.code == \"GSG_X\" or r.code == \"GSG_Y\" or r.code == \"GSG_Z\") and\r\n      r._field == \"value_num\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"code\"])\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "DUS2 - Distanca",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      r.code == \"DUS2\" and\r\n      r._field == \"value_num\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "DHT3 — vlažnost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      r.code == \"DHT3_HUM\" and\r\n      r._field == \"value_num\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "DHT3 — temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"telemetry\" and\r\n      r.device == \"PI2\" and\r\n      r.code == \"DHT3_TEMP\" and\r\n      r._field == \"value_num\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "DPIR2 — detekcija pokreta",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r.code == \"DPIR2\")\r\n  |> filter(fn: (r) => r._field == \"value_bool\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "DS2 - Otvaranje/zatvaranje",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r.device == \"PI2\" and\r\n      r.code == \"DS2\" and\r\n      r._field == \"value_bool\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\r\n"
    }
   ]
  },
  {
   "title": "BTN - kuhinjsko dugme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r.device == \"PI2\" and\r\n      r.code == \"BTN\" and\r\n      r._field == \"value_bool\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\r\n"
    }
   ]
  }
 ]
}