{
 "title": "pi3",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DPIR3",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r.code == \"DPIR3\")\r\n  |> filter(fn: (r) => r._field == \"value_bool\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "DHT1 i DHT2- vlaznost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"telemetry\" and\r\n    r.device == \"PI3\" and\r\n    (r.code == \"DHT1_HUM\" or r.code == \"DHT2_HUM\") and\r\n    r._field == \"value_num\"\r\n  )"
    }
   ]
  },
  {
   "title": "BGRB",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"telemetry\" and\r\n    r.device == \"PI3\" and\r\n    r.code == \"BRGB_SET\" and\r\n    r._field == \"value_str\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      rr: if strings.containsStr(v: string(v: r._value), substr: \"'r': True\") then 1 else 0,\r\n      gg: if strings.containsStr(v: string(v: r._value), substr: \"'g': True\") then 1 else 0,\r\n      bb: if strings.containsStr(v: string(v: r._value), substr: \"'b': True\") then 1 else 0,\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r.rr * 4 + r.gg * 2 + r.bb,\r\n      _field: \"BRGB\"          // jedan field da bude jedna serija\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "DHT1 i DHT2 - temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"telemetry\" and\r\n    r.device == \"PI3\" and\r\n    (r.code == \"DHT1_TEMP\" or r.code == \"DHT2_TEMP\") and\r\n    r._field == \"value_num\"\r\n  )"
    }
   ]
  }
 ]
}